version: '3.9'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "3000:8080"
    volumes:
      - ./api/openapi.json:/openapi.json
    environment:
      SWAGGER_JSON: /openapi.json